name: Machine Learning Workflow

on:
  push:
    branches: [ main ]

jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run Training Directly
        run: |
          # Sapu bersih semua folder mlruns di seluruh direktori
          rm -rf mlruns
          rm -rf ML_Project/mlruns
          
          # Jalankan tanpa dipengaruhi environment lama
          export MLFLOW_TRACKING_URI=file:$(pwd)/mlruns
          mlflow run ML_Project --env-manager=local

      - name: Simpan Artefak
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: model-hasil-retraining
          path: ML_Project/mlruns/
